[package]
name = "tfswitcher"
version = "0.2.4"
edition = "2021"
authors = ["ASleepyCat dyeom340@gmail.com"]
license = "MIT"
description = "Terraform version switcher written (mostly) in Rust"
readme = "README.md"
repository = "https://github.com/ASleepyCat/tfswitcher"
keywords = ["cli", "terraform", "tfswitcher", "tfswitch"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.4.4", features = ["derive", "env"] }
dialoguer = "0.10.4"
home = "0.5.4"
html-to-string-macro = "0.2.5"
once_cell = "1.18.0"
pathsearch = "0.2.0"
regex = "1.9.5"
reqwest = { version = "0.11.20", features = ["json", "blocking"] }
semver = { version = "1.0.17", package = "tf-semver" }
tempdir = "0.3.7"
tfconfig = "0.2.1"
zip = "0.6.4"
