[package]
name = "tfswitcher"
version = "0.2.1"
edition = "2021"
authors = ["ASleepyCat dyeom340@gmail.com"]
license = "MIT"
description = "Terraform version switcher written (mostly) in Rust"
readme = "README.md"
repository = "https://github.com/ASleepyCat/tfswitcher"
keywords = ["cli", "terraform", "tfswitcher", "tfswitch"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.12", features = ["derive", "env"] }
dialoguer = "0.10.4"
home = "0.5.4"
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["json", "blocking"] }
semver = { version = "1.0.17", package = "tf-semver" }
tempdir = "0.3.7"
tfconfig = "0.1.0"
zip = "0.6.4"
