[package]
name = "tfswitcher"
version = "0.1.0"
edition = "2021"
authors = ["ASleepyCat dyeom340@gmail.com"]
license = "MIT"
description = "Terraform version switcher written (mostly) in Rust"
readme = "README.md"
repository = "https://github.com/ASleepyCat/tfswitcher"
keywords = ["cli", "terraform", "tfswitcher", "tfswitch"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.5", features = ["derive", "env"] }
dialoguer = "0.10.4"
home = "0.5.4"
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["json", "blocking"] }
semver = "1.0.17"
tempdir = "0.3.7"
zip = "0.6.4"

[build-dependencies]
gobuild = "0.1.0-alpha.2"

[patch.crates-io]
gobuild = { git = "https://github.com/ASleepyCat/gobuild", branch = "fix-spaces-in-path" }
semver = { git = "https://github.com/ASleepyCat/semver", branch = "tilde-arrow" }
