[package]
name = "tfswitcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.4"
home = "0.5.4"
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["json", "blocking"] }
semver = { git = "https://github.com/ASleepyCat/semver", branch = "tilde-arrow" }
zip = "0.6.4"

[build-dependencies]
gobuild = "0.1.0-alpha.2"
