[package]
name = "tfswitcher"
version = "0.3.0"
edition = "2021"
authors = ["ASleepyCat dyeom340@gmail.com"]
license = "MIT"
description = "A Terraform version switcher"
readme = "README.md"
repository = "https://github.com/ASleepyCat/tfswitcher"
keywords = ["cli", "terraform", "tfswitcher", "tfswitch"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.4.6", features = ["cargo", "derive", "env"] }
clap_complete = "4.4.3"
dialoguer = "0.11.0"
home = "0.5.4"
html-to-string-macro = "0.2.5"
once_cell = "1.18.0"
pathsearch = "0.2.0"
regex = "1.9.6"
reqwest = { version = "0.11.22", features = ["json", "blocking"] }
semver = { version = "1.0.17", package = "tf-semver" }
serde = { version = "1.0.188", features = ["derive"] }
tempdir = "0.3.7"
tfconfig = "0.2.2"
toml = "0.8.2"
zip = "0.6.4"
