name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true

  homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ASleepyCat/homebrew-tap
      - name: Update Formula
        run: |
          cat <<EOF > Formula/tfswitcher.rb
          class Tfswitcher < Formula
            desc "Terraform and OpenTofu version switcher"
            homepage "https://github.com/ASleepyCat/tfswitcher"
            url "https://github.com/ASleepyCat/tfswitcher/archive/refs/tags/${{ github.event.release.tag_name }}.tar.gz"
            sha256 "$(curl -sL https://codeload.github.com/ASleepyCat/tfswitcher/tar.gz/refs/tags/${{ github.event.release.tag_name }} | sha256sum | cut -d " " -f1)"
            license "MIT"

            depends_on "openssl" => :build
            depends_on "pkg-config" => :build
            depends_on "rust" => :build

            # TODO: Add OpenTofu when it gets added to homebrew-core
            conflicts_with "terraform", because: "tfswitcher overwrites the current terraform install"

            def install
              system "cargo", "install", *std_cargo_args
            end

            test do
              assert_match "tfswitcher #{version}", shell_output("#{bin}/tfswitcher -V")
            end
          end
          EOF
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: ASleepyCat
          destination-repository-name: homebrew-tap
          user-email: dyeom340@gmail.com
          target-branch: main
          commit-message: Update tfswitcher Formula to ${{ github.event.release.tag_name }}

  release:
    name: Release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tfswitcher-${{ github.event.release.tag_name }}-x86_64-unknown-linux-gnu.tar.gz
            archive-command: tar caf
            sha256-command: sha256sum
            bin: tfswitcher
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: tfswitcher-${{ github.event.release.tag_name }}-x86_64-pc-windows-msvc.zip
            archive-command: 7z a
            bin: tfswitcher.exe
            sha256-command: sha256sum
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: tfswitcher-${{ github.event.release.tag_name }}-x86_64-apple-darwin.zip
            archive-command: zip -9
            sha256-command: shasum -a 256
            bin: tfswitcher
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Compile
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
      - name: Get upload URL
        id: get_upload_url
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create release assets
        working-directory: target/${{ matrix.target }}/release
        run: |
          ${{ matrix.archive-command }} ${{ matrix.archive }} ${{ matrix.bin }}
          ${{ matrix.sha256-command }} ${{ matrix.archive }} > ${{ matrix.archive }}.sha256sum
      - name: Upload archive
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: target/${{ matrix.target }}/release/${{ matrix.archive }}
          asset_name: ${{ matrix.archive }}
          asset_content_type: application/octet-stream
      - name: Upload SHA256
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: target/${{ matrix.target }}/release/${{ matrix.archive }}.sha256sum
          asset_name: ${{ matrix.archive }}.sha256sum
          asset_content_type: text/plain
